### ISSUE TITLE
grad为none

### ISSUE THREAD

**Issue by HereNowL** [lorenmt/auto-lambda#10]
作者您好，非常感谢您精彩的工作，最近我在尝试应用时遇到了这样一个问题，我使用‘语义分割’和‘深度估计’作为主要任务，也就是说最终有两条分支进行任务预测，分别为语义分割和深度估计。但我使用auto_lambda.py中的virtual_step求解梯度时，gradients = torch.autograd.grad(loss, self.model.parameters(), allow_unused=True)，总有一部分梯度为None，我打印了梯度为None的参数，发现都是第二个任务‘深度估计’的分支结构。在去掉auto_lambda的情况下，使用backward，是没有问题的，想请教一下可能是哪里出现了问题呢？再次感谢！

**Comment by lorenmt** [comment]
你好, 感谢你对我的工作的肯定. 在正常backward的过程中, 梯度为None 也不会影响传播. virtual step里需要 因为需要进行加减运算. 因此我猜测你的网络结构在forward depth的时候 有一部参数没有进行运算. 所以你要么手动设置这些梯度为0, 要么把他加入计算, 一个最弱智的方法就是 过那部分你不想要的参数 但是最后累加的时候乘以0 系数也就不影响你的  loss, 但是梯度都会计算切归0.

**Comment by HereNowL** [comment]
作者您好，感谢您的解答，我已经将不参与运算的网络层去掉，但我重新在virtual_step中查看梯度为none的网络参数，发现整个网络梯度都是为none，请问您有什么经验或技巧能够帮助我排查错误吗？十分感谢！

**Comment by lorenmt** [comment]
说明你的loss 压根没经过网络计算....你先从random input查看到底哪里有问题..

**Comment by HereNowL** [comment]
作者您好，我再次排查了bug，还是有一部分参数为none，集中在‘深度估计’的网络层。让我感到很疑惑的是，我设计的网络，对于两个任务分支结构完全相同，为什么只有一个任务没有梯度呢？

**Comment by HereNowL** [comment]
作者您好，这个问题已经解决了，多个loss加和只回传了一个loss，导致部分网络分支梯度为none。
