### ISSUE TITLE
Can we do Multiple Classification task

### ISSUE THREAD

**Issue by akirs82** [lorenmt/auto-lambda#11]
Hello lorentmt,

Kudos to the great work. I just want to know if we can use this repo to train multiple classification tasks. For example Vehicle Make ,Color,Orientation,Model - each 4 attributes as individual tasks.

regards
akirs

**Comment by lorenmt** [comment]
Hello, yes.

Are these four attributes from the same image? If so, you should follow the training script in "trainer_dense" and modify the task-specific prediction layers: https://github.com/lorenmt/auto-lambda/blob/bdba6365953f7ebb3a8ae33fabfecd3f933ecc27/create_network.py#L161-L162

**Comment by akirs82** [comment]
Hello lorentmt,

Thanks for the quick reply. Yes,I need to pass the same image for all the four tasks. Just to be clear Vehicle Make = Hyundai,BMW,Ford etc, Vehicle Color = White,Silver,Blue etc, Vehicle Orientation= front,rear,others, Vehicle Model = Hyundai_i10,Hyundai_i20 etc.  There is no auxiliary/segmentation kind of tasks. Instead of "trainer_dense" should I use the "trainer_cifar" script as this is only image classification task?

In your project page [here](https://shikun.io/projects/auto-lambda#:~:text=Training%20Speed%3A,alternative%20optimisation%20methods.) you have mentioned that training requireds second-order derivative computation. I just want to know,in case of inference also will it be still slow/ or if you can point me to any speed benchmarks ?   

regards
akirs

**Comment by lorenmt** [comment]
trainer_cifar is training classification tasks but in a multi-domain setting, i.e training multiple datasets into a single network. Probably it would be easier to modify the classification architecture to fit your tasks, and then use trainer_dense to train it.

The training time would be roughly three times slower using a first-order approximation. If your dataset is not super large it should be pretty fast to train. But you can start with standard MTL with equal weightings to get the baseline performance.

**Comment by akirs82** [comment]
Sure thanks,will try it out and get back in case of any queries.
