### ISSUE TITLE
failed to download the NYU npy dataset

### ISSUE THREAD

**Issue by Rui-Zhou-2** [lorenmt/auto-lambda#3]
Hello, I tried many times to download the NYU npy file from the dropbox link, but it always failed in the last minutes.

I am confusing about the problem because the code can only support the npy format...may be there is some preprocess code for NYU?

With best regards

**Comment by lorenmt** [comment]
hello, yes the dataset was preprocessed from my previous project here: https://github.com/lorenmt/mtan.

But unfortunately I am not able to provide the preprocessing code…

but I haven’t heard from anyone having the downloading issue. Were you using VPN?

**Comment by Rui-Zhou-2** [comment]
Yes, I am using VPN, and it can download most part but fail in the last second...

**Comment by lorenmt** [comment]
I have received similar concerns from other people using VPN...Unfortunately I have no other ways to help on this issue.

Maybe try different hosting countries?

**Comment by Rui-Zhou-2** [comment]
I tried many times but still failed... 

Maybe you could provide a link for google drive?
That will work well.😊

With great thanks

**Comment by lorenmt** [comment]
Sorry I don't have much free space for Google Drive.
I further split the file for train and val with the links as follows:
https://www.dropbox.com/sh/pfrxmas4ygvgi0m/AABysAoWgxelSBVYVnOOfCQta?dl=0
https://www.dropbox.com/sh/ynckbqe9xkhe4uf/AACjXxOWWLRq63VLoqjyAcsIa?dl=0

Could you try whether this works?

**Comment by lorenmt** [comment]
Alterantively you can use wget.. maybe that's more stable?

**Comment by Rui-Zhou-2** [comment]
> Sorry I don't have much free space for Google Drive. I further split the file for train and val with the links as follows: https://www.dropbox.com/sh/pfrxmas4ygvgi0m/AABysAoWgxelSBVYVnOOfCQta?dl=0 https://www.dropbox.com/sh/ynckbqe9xkhe4uf/AACjXxOWWLRq63VLoqjyAcsIa?dl=0
> 
> Could you try whether this works?

This file works! Thank you so much!

one more question: have you saved any model weights?

**Comment by lorenmt** [comment]
Sorry no. The dataset is relatively small and can be trained from scratch within 8 hours in a single GPU, so I did not save any model weights.

**Comment by Rui-Zhou-2** [comment]
Thank you for reply. I will close this issue.
