### ISSUE TITLE
No module named "***"

### ISSUE THREAD

**Issue by liusidi** [lorenmt/auto-lambda#7]
![E76HPZMWBX5$KA66{MSP%9U](https://user-images.githubusercontent.com/77909255/188252927-66f3d183-173c-4cd2-bb9c-5e3d96511865.png)
A problem occurred when I ran the Cityscape dataset, unable to import the defined modules correctly.

**Comment by lorenmt** [comment]
Well...Maybe move utils/__init__.py to utils.py? See whether this will work?  Otherwise you may install the entire package from https://github.com/pmeletis/panoptic_parts.

You can clearly see the function defined in init.. so just try to map it correctly. I don't have such issue from my end.

**Comment by liusidi** [comment]
Thank you for your reply. I will try the method you said.

**Comment by liusidi** [comment]
After solving the above problem, there is another problem.There was a problem when I ran trainer-dense.py。
![PR}(2~DFR9{X28N_%X$)J@6](https://user-images.githubusercontent.com/77909255/188295771-532e25f0-3c9e-48b4-a57e-def602d4f330.png)

**Comment by lorenmt** [comment]
Sorry I am not able to reproduce your problem. It seems that your data files are wrong.
Could you just pip install panoptic_parts, and make sure the CityScapes files are correct?

**Comment by liusidi** [comment]
Thank you for your answer. The problem has been solved.
