### ISSUE TITLE
损失函数为Nan

### ISSUE THREAD

**Issue by raozhongyu** [lorenmt/auto-lambda#9]
博主您好，非常感谢您的工作，近期我尝试用auto-lambda来优化自己的模型，因为自己的模型中存在一些无法求导的参数，因此我尝试将求取梯度改为以下部分：
    model_params = [
               p for p in self.model.parameters() if p.requires_grad
        ]
gradients = torch.autograd.grad(loss, shared_params,retain_graph=True,allow_unused=True)
但是这样就存在一些梯度层为None,我个人直接做了一个if判定，直接不操作这些为None的层，代码跑通了，但是训练过程中存在loss
指数上升最后为Nan的情况：
 0%|          | 1/11807 [01:52<369:46:10, 112.75s/it]tensor(31.6492, device='cuda:0', grad_fn=<AddBackward0>)
  0%|          | 2/11807 [01:53<259:48:03, 79.23s/it] tensor(408.9402, device='cuda:0', grad_fn=<AddBackward0>)
  0%|          | 3/11807 [01:54<182:54:59, 55.79s/it]tensor(43848.0703, device='cuda:0', grad_fn=<AddBackward0>)
  0%|          | 4/11807 [01:55<129:05:55, 39.38s/it]tensor(1.1228e+15, device='cuda:0', grad_fn=<AddBackward0>)
  0%|          | 5/11807 [01:56<91:24:46, 27.88s/it] tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
  0%|          | 6/11807 [01:58<65:00:37, 19.83s/it]tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
  0%|          | 7/11807 [01:59<46:34:15, 14.21s/it]tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
  0%|          | 8/11807 [02:00<33:45:58, 10.30s/it]tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
  0%|          | 9/11807 [02:01<24:43:29,  7.54s/it]tensor(nan, device='cuda:0', grad_fn=<AddBackward0>)
  0%|          | 10/11807 [02:02<18:18:33,  5.59s/it]Traceback (most recent call last):
想请教一下您，看看有没有什么建议

**Comment by lorenmt** [comment]
如果你模型里有fixed parameter 就不应该放到optimiser里, 或者放到parameter_list 里...如果放到optimiser里就一定是可求导的...你能否先确定在不用auto-lambda的情况下代码能跑通?

**Comment by raozhongyu** [comment]
在不用auto-lambda的情况下是可以跑通代码的,
model_params = [
p for p in self.model.parameters() if p.requires_grad
]
我的这个代码是不是已经可以将fixed paramter剔除出去

**Comment by lorenmt** [comment]
理论上是的..那你optimiser也是这么写的么?
最好的办法是你在model init里就不把param作为模型参数..只要定义torch.tensor(xx, requires_grad=False)应该就行

**Comment by raozhongyu** [comment]
好的，感谢博主，我试一试



---原始邮件---
发件人: "Shikun ***@***.***&gt;
发送时间: 2022年11月22日(周二) 晚上10:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lorenmt/auto-lambda] 损失函数为Nan (Issue #9)




 
理论上是的..那你optimiser也是这么写的么?
 最好的办法是你在model init里就不把param作为模型参数..只要定义torch.tensor(xx, requires_grad=False)应该就行

**Comment by lorenmt** [comment]
有任何更新么？

**Comment by raozhongyu** [comment]
我尝试了一下，解决了nan的问题，好像是跟初始化权重有关，但是效果不是太好，我这边再试试，感谢博主🙏



---原始邮件---
发件人: "Shikun ***@***.***&gt;
发送时间: 2022年11月24日(周四) 晚上11:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lorenmt/auto-lambda] 损失函数为Nan (Issue #9)




 
有任何更新么？

**Comment by lorenmt** [comment]
好的。Auto-Lambda 可能比较sensitive to task weight initialisation 和 learning rate。有其他问题欢迎继续跟进。
